# scripts/bootstrap_gdelt_history.py

"""
Reprocess stored GDELT history with the CURRENT event builder.

Purpose
-------
Historical GDELT JSONL records may still contain only the legacy `topics`
field. This migration rebuilds records stored under:

    data/events/gdelt/*.jsonl

through the current pipeline.event_builder.build_event(), so historical GDELT
events receive topic_scores, topic_salience, topic_details and the current
topic detector metadata.

Important
---------
This script DOES NOT download new GDELT data. It only migrates already stored
history. The normal GDELT collector remains responsible for new events.

Safety
------
- Existing JSONL files are rewritten atomically through a temporary file.
- Original event order is preserved.
- Invalid JSON lines are kept unchanged.
- Unknown/source-specific legacy fields are preserved.
- Existing timestamps, URL and metadata are retained where available.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from pipeline.event_builder import build_event


GDELT_EVENTS_DIR = ROOT_DIR / "data" / "events" / "gdelt"
EXPECTED_TOPIC_METHOD = "rule_based_topic_salience_v2"


def _string(value: Any) -> str:
    return "" if value is None else str(value)


def _first(event: Dict[str, Any], *keys: str) -> Any:
    for key in keys:
        value = event.get(key)
        if value not in (None, ""):
            return value
    return None


def rebuild_event(old_event: Dict[str, Any]) -> Dict[str, Any]:
    """
    Rebuild one stored GDELT event with the current event schema.

    Common legacy GDELT aliases are accepted defensively. Any source-specific
    top-level fields not generated by build_event() are copied back afterwards.
    """
    old_metadata = old_event.get("metadata")
    if not isinstance(old_metadata, dict):
        old_metadata = {}

    metadata = dict(old_metadata)
    metadata["history_reprocessed"] = True
    metadata["history_reprocess_source_schema"] = old_event.get(
        "schema_version",
        "legacy_or_unknown",
    )

    # Keep useful GDELT identifiers inside metadata as well, while original
    # top-level fields are preserved below.
    for source_key in (
        "GlobalEventID",
        "global_event_id",
        "globaleventid",
        "gdelt_event_id",
        "event_id",
    ):
        if old_event.get(source_key) not in (None, ""):
            metadata.setdefault(
                "gdelt_event_id",
                old_event.get(source_key),
            )
            break

    source_name = _first(
        old_event,
        "source_name",
        "source",
        "publisher",
        "domain",
        "source_domain",
    )

    title = _first(
        old_event,
        "title",
        "headline",
        "name",
    )

    summary = _first(
        old_event,
        "summary",
        "description",
        "snippet",
        "seendescription",
    )

    body = _first(
        old_event,
        "body",
        "content",
        "text",
        "article_text",
    )

    url = _first(
        old_event,
        "url",
        "link",
        "article_url",
        "source_url",
        "DocumentIdentifier",
        "document_identifier",
    )

    published_at = _first(
        old_event,
        "published_at",
        "published",
        "publication_date",
        "date",
        "datetime",
        "timestamp",
        "SQLDATE",
        "sqldate",
    )

    collected_at = _first(
        old_event,
        "collected_at",
        "ingested_at",
        "fetched_at",
        "created_at",
    )

    rebuilt = build_event(
        layer="gdelt",
        source_name=_string(source_name or "GDELT"),
        title=_string(title),
        summary=_string(summary),
        body=_string(body),
        url=_string(url),
        published_at=published_at,
        collected_at=collected_at,
        source_type=_string(
            old_event.get("source_type")
            or "gdelt"
        ),
        metadata=metadata,
    )

    # Preserve all GDELT/source-specific fields that are not part of the
    # current generic event schema. Freshly rebuilt fields always win.
    for key, value in old_event.items():
        if key not in rebuilt:
            rebuilt[key] = value

    return rebuilt


def migrate_file(path: Path) -> Dict[str, int]:
    output_lines: List[str] = []
    stats = Counter()

    with path.open("r", encoding="utf-8") as handle:
        for line_number, raw_line in enumerate(handle, start=1):
            stripped = raw_line.strip()

            if not stripped:
                continue

            stats["lines_seen"] += 1

            try:
                old_event = json.loads(stripped)
            except json.JSONDecodeError:
                output_lines.append(stripped)
                stats["invalid_json_preserved"] += 1
                continue

            if not isinstance(old_event, dict):
                output_lines.append(
                    json.dumps(
                        old_event,
                        ensure_ascii=False,
                    )
                )
                stats["non_object_preserved"] += 1
                continue

            try:
                rebuilt = rebuild_event(old_event)
            except Exception as exc:
                print(
                    f"WARNING: {path.name}:{line_number} rebuild failed: "
                    f"{type(exc).__name__}: {exc}"
                )
                output_lines.append(
                    json.dumps(
                        old_event,
                        ensure_ascii=False,
                    )
                )
                stats["rebuild_failed_preserved"] += 1
                continue

            output_lines.append(
                json.dumps(
                    rebuilt,
                    ensure_ascii=False,
                )
            )
            stats["rebuilt"] += 1

            if rebuilt.get("topic_salience"):
                stats["with_topic_salience"] += 1
            else:
                stats["without_topic_salience"] += 1

            method = str(
                rebuilt.get("topic_method")
                or "missing"
            )
            stats[f"method::{method}"] += 1

    temp_path = path.with_suffix(
        path.suffix + ".tmp"
    )

    with temp_path.open(
        "w",
        encoding="utf-8",
        newline="\n",
    ) as handle:
        for line in output_lines:
            handle.write(line + "\n")

    # Atomic replacement on the same filesystem.
    temp_path.replace(path)

    return dict(stats)


def find_history_files() -> List[Path]:
    if not GDELT_EVENTS_DIR.exists():
        return []

    return sorted(
        path
        for path in GDELT_EVENTS_DIR.glob("*.jsonl")
        if path.is_file()
    )


def main() -> None:
    print("Starting GDELT historical event reprocessing...")
    print(f"GDELT history directory: {GDELT_EVENTS_DIR}")

    files = find_history_files()

    if not files:
        print("No GDELT history JSONL files found. Nothing to reprocess.")
        return

    print(f"History files found: {len(files)}")

    total = Counter()

    for index, path in enumerate(files, start=1):
        print(
            f"[{index}/{len(files)}] "
            f"Reprocessing {path.name}..."
        )

        result = migrate_file(path)
        total.update(result)

        print(
            "  rebuilt={rebuilt} | salience={salience} | "
            "without_salience={without} | invalid_preserved={invalid}".format(
                rebuilt=result.get("rebuilt", 0),
                salience=result.get(
                    "with_topic_salience",
                    0,
                ),
                without=result.get(
                    "without_topic_salience",
                    0,
                ),
                invalid=result.get(
                    "invalid_json_preserved",
                    0,
                ),
            )
        )

    print("\nGDELT history migration summary")
    print("-------------------------------")
    print(f"Files processed: {len(files)}")
    print(
        f"JSON records seen: "
        f"{total.get('lines_seen', 0)}"
    )
    print(
        f"Events rebuilt: "
        f"{total.get('rebuilt', 0)}"
    )
    print(
        "Events with topic_salience: "
        f"{total.get('with_topic_salience', 0)}"
    )
    print(
        "Events without topic_salience: "
        f"{total.get('without_topic_salience', 0)}"
    )
    print(
        "Invalid JSON lines preserved: "
        f"{total.get('invalid_json_preserved', 0)}"
    )
    print(
        "Rebuild failures preserved: "
        f"{total.get('rebuild_failed_preserved', 0)}"
    )

    method_counts = {
        key.split("method::", 1)[1]: value
        for key, value in total.items()
        if key.startswith("method::")
    }

    print("\nTopic methods after migration:")

    if method_counts:
        for method, count in sorted(
            method_counts.items(),
            key=lambda item: (
                -item[1],
                item[0],
            ),
        ):
            print(
                f"  {method}: {count}"
            )
    else:
        print("  none")

    expected_count = method_counts.get(
        EXPECTED_TOPIC_METHOD,
        0,
    )

    print("\nValidation")
    print("----------")

    if expected_count:
        print(
            f"OK: {expected_count} events use "
            f"{EXPECTED_TOPIC_METHOD}."
        )
    else:
        print(
            "WARNING: no event reports the expected topic method "
            f"{EXPECTED_TOPIC_METHOD}."
        )

    if total.get("without_topic_salience", 0):
        print(
            "NOTE: events without topic_salience may contain no configured "
            "topic keyword or may have too little source text."
        )

    print(
        "\nGDELT historical reprocessing finished successfully."
    )
    print(
        "Next: run scripts/build_window_networks.py and inspect "
        "topic_metadata.event_topic_method_counts in combined/30d outputs."
    )


if __name__ == "__main__":
    main()

